### ISSUE TITLE
TODO, FIXME, NOTE

### ISSUE THREAD

**Issue by HrvojeJuric** [altibiz/ozds#35]
- [ ] go over all TODO's in code and create issues
- [ ] go over all FIXME's in code and create issues
- [ ] go over all NOTE's and decide what to do with them

**Comment by HrvojeJuric** [comment]
solved but also a shit issue
